---
- name: download and extract kubernetes {{ kubernetes_version }} server tarball
  unarchive:
    src: "https://dl.k8s.io/{{ kubernetes_version }}/kubernetes-server-linux-arm.tar.gz"
    remote_src: true
    dest: /home/{{ ansible_user }}
    # only extracts what is needed (bin folder)
    extra_opts:
    - --strip=2
    - --wildcards
    - '*/bin'
    creates: /home/{{ ansible_user }}/bin
  tags:
  - controlplane
- name: move kubeadm kubectl and kubelet binaries to /usr/bin
  copy:
    src: /home/{{ ansible_user }}/bin/{{ item }}
    dest: /usr/bin/{{ item }}
    remote_src: true
    mode: a+x
  with_items:
     - kubeadm
     - kubectl
     - kubelet
     - kube-proxy
  tags:
  - controlplane
- name: load docker containers from server binaries
  # these are all publically available but will save some time on init.
  shell: docker load -i /home/{{ ansible_user }}/bin/{{ item }}.tar
  with_items:
     - kube-apiserver
     - kube-controller-manager
     - kube-scheduler
     - kube-proxy
  tags:
  - controlplane
- name: enable and start service kubelet
  service:
    name: kubelet
    daemon_reload: yes
    enabled: yes
  tags:
  - controlplane
- name: create kubeadm config file
  template:
    src: ../../files/kubeadm-config.j2
    dest: /home/{{ ansible_user }}/kubeadm-config.yaml
  tags:
  - kubeadmconf
  - controlplane
- name: Check if /etc/kubernetes/admin.conf exists
  stat:
    path: /etc/kubernetes/admin.conf
  register: admin_conf
  tags:
  - kubernetes-status
  - controlplane
- name: init kubeadm (bootstrap control plane)
  shell: kubeadm init --config=/home/{{ ansible_user }}/kubeadm-config.yaml
  when: not admin_conf.stat.exists
  notify: kubectl apply cni
  tags:
  - controlplane
- name: Create $HOME/.kube for kubectl
  file:
    path: /home/{{ ansible_user }}/.kube
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  tags:
  - kubectl
- name: move admin.conf kubeconfig to home directory
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/{{ ansible_user }}/.kube/config
    remote_src: true
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  tags:
  - kubectl