---
- name: wait for admin.conf
  wait_for:
    path: /etc/kubernetes/admin.conf
  listen: "apply cni"
- name: install weaveworks cni
  shell: |
    export KUBECONFIG=/etc/kubernetes/admin.conf
    kubectl wait --namespace=kube-system --for=condition=Ready pods --selector tier=control-plane --timeout=600s
    kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
  listen: "apply cni"